// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	models "github.com/abyanjksatu/goscription/models"
	mock "github.com/stretchr/testify/mock"
)

// DomainService is an autogenerated mock type for the DomainService type
type DomainService struct {
	mock.Mock
}

// GetDomainAvailable provides a mock function with given fields: _a0
func (_m *DomainService) GetDomainAvailable(_a0 string) (models.DomainAvailableResponse, error) {
	ret := _m.Called(_a0)

	var r0 models.DomainAvailableResponse
	if rf, ok := ret.Get(0).(func(string) models.DomainAvailableResponse); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(models.DomainAvailableResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
