// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	models "github.com/abyanjksatu/goscription/models"
	mock "github.com/stretchr/testify/mock"
)

// GodaddyOutbound is an autogenerated mock type for the GodaddyOutbound type
type GodaddyOutbound struct {
	mock.Mock
}

// GetDomainAvailable provides a mock function with given fields: domain
func (_m *GodaddyOutbound) GetDomainAvailable(domain string) (models.DomainAvailableResponse, error) {
	ret := _m.Called(domain)

	var r0 models.DomainAvailableResponse
	if rf, ok := ret.Get(0).(func(string) models.DomainAvailableResponse); ok {
		r0 = rf(domain)
	} else {
		r0 = ret.Get(0).(models.DomainAvailableResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
